### ISSUE TITLE
No requirement file found

### ISSUE THREAD

**Issue by vidhi-saxena02** [akeshya/Jewellery_App#1]
Can you provide a file with the task we have to do in this project for submission?

**Comment by TirthNisar193** [comment]
Yes what changes do we exactly have to make can someone help

**Comment by akeshya** [comment]
# Hi 
**Are you able to setup the environment first?** 

**If yes, _then please list out all the bugs and open issues for those bugs repo._ **

**Comment by vidhi-saxena02** [comment]
I have created a new issue.
